# Generated by Django 5.2.3 on 2025-06-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diary',
            new_name='Entry',
        ),
    ]
