# Generated by Django 5.2.3 on 2025-06-18 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_entry_updated_at_alter_entry_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='emotion',
            field=models.CharField(choices=[('happy', '행복'), ('sad', '슬픔'), ('angry', '분노'), ('neutral', '중립'), ('anxious', '불안')], default='neutral', max_length=10),
        ),
    ]
