# Generated by Django 5.2.3 on 2025-06-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_entry_author_entry_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='emotion',
            field=models.CharField(choices=[('happy', '행복'), ('sad', '슬픔'), ('angry', '분노'), ('joy', '즐거움'), ('lethargy', '무기력')], default='neutral', max_length=10),
        ),
    ]
